#!/bin/sh

cd `dirname $0`/..

DEPLOY_IMAGE_DIR=.deploy_image

rm -r ${DEPLOY_IMAGE_DIR} 2>/dev/null
mkdir ${DEPLOY_IMAGE_DIR}

echo "Copying game..."
cp -R build/Release_SDL/GZDoom.app ${DEPLOY_IMAGE_DIR}

echo "Stripping executable..."
strip ${DEPLOY_IMAGE_DIR}/GZDoom.app/Contents/MacOS/GZDoom

echo "Copying documentation..."
mkdir ${DEPLOY_IMAGE_DIR}/Documentation
cp -R docs/ ${DEPLOY_IMAGE_DIR}/Documentation
cp ReadMe.rtf ${DEPLOY_IMAGE_DIR}

echo "Building image..."
hdiutil create -srcfolder ${DEPLOY_IMAGE_DIR} -volname GZDoom ${DEPLOY_IMAGE_DIR}/GZDoom.dmg
