
#include "g_doom/a_doommisc.cpp"

#include "g_heretic/a_hereticmisc.cpp"

#include "g_hexen/a_hexenmisc.cpp"

#include "g_raven/a_artitele.cpp"
#include "g_raven/a_minotaur.cpp"

#include "g_shared/a_action.cpp"
#include "g_shared/a_armor.cpp"
#include "g_shared/a_artifacts.cpp"
#include "g_shared/a_bridge.cpp"
#include "g_shared/a_camera.cpp"
#include "g_shared/a_debris.cpp"
#include "g_shared/a_decals.cpp"
#include "g_shared/a_fastprojectile.cpp"
#include "g_shared/a_flashfader.cpp"
#include "g_shared/a_fountain.cpp"
#include "g_shared/a_hatetarget.cpp"
#include "g_shared/a_keys.cpp"
#include "g_shared/a_lightning.cpp"
#include "g_shared/a_mapmarker.cpp"
#include "g_shared/a_morph.cpp"
#include "g_shared/a_movingcamera.cpp"
#include "g_shared/a_pickups.cpp"
#include "g_shared/a_puzzleitems.cpp"
#include "g_shared/a_quake.cpp"
#include "g_shared/a_randomspawner.cpp"
#include "g_shared/a_secrettrigger.cpp"
#include "g_shared/a_sectoraction.cpp"
#include "g_shared/a_setcolor.cpp"
#include "g_shared/a_skies.cpp"
#include "g_shared/a_soundenvironment.cpp"
#include "g_shared/a_soundsequence.cpp"
#include "g_shared/a_spark.cpp"
#include "g_shared/a_specialspot.cpp"
#include "g_shared/a_waterzone.cpp"
#include "g_shared/a_weaponpiece.cpp"
#include "g_shared/a_weapons.cpp"
#include "g_shared/hudmessages.cpp"
#include "g_shared/sbar_mugshot.cpp"
#include "g_shared/sbarinfo.cpp"
#include "g_shared/shared_hud.cpp"
#include "g_shared/shared_sbar.cpp"

#include "g_strife/a_strifestuff.cpp"
#include "g_strife/strife_sbar.cpp"
