
#include "r_data/colormaps.cpp"
#include "r_data/r_interpolate.cpp"
#include "r_data/r_translate.cpp"
#include "r_data/renderstyle.cpp"
#include "r_data/sprites.cpp"
#include "r_data/voxels.cpp"

#include "resourcefiles/ancientzip.cpp"
#include "resourcefiles/file_7z.cpp"
#include "resourcefiles/file_directory.cpp"
#include "resourcefiles/file_grp.cpp"
#include "resourcefiles/file_lump.cpp"
#include "resourcefiles/file_pak.cpp"
#include "resourcefiles/file_rff.cpp"
#include "resourcefiles/file_wad.cpp"
#include "resourcefiles/file_zip.cpp"
#include "resourcefiles/resourcefile.cpp"

#include "sfmt/SFMT.cpp"

#include "textures/anim_switches.cpp"
#include "textures/animations.cpp"
#include "textures/automaptexture.cpp"
#include "textures/bitmap.cpp"
#include "textures/buildtexture.cpp"
#include "textures/canvastexture.cpp"
#include "textures/ddstexture.cpp"
#include "textures/emptytexture.cpp"
#include "textures/flattexture.cpp"
#include "textures/imgztexture.cpp"
#include "textures/jpegtexture.cpp"
#include "textures/multipatchtexture.cpp"
#include "textures/patchtexture.cpp"
#include "textures/pcxtexture.cpp"
#include "textures/pngtexture.cpp"
#include "textures/rawpagetexture.cpp"
#include "textures/texture.cpp"
#include "textures/texturemanager.cpp"
#include "textures/tgatexture.cpp"
#include "textures/warptexture.cpp"

#include "thingdef/olddecorations.cpp"
#include "thingdef/thingdef.cpp"
#include "thingdef/thingdef_codeptr.cpp"
#include "thingdef/thingdef_data.cpp"
#include "thingdef/thingdef_exp.cpp"
#include "thingdef/thingdef_expression.cpp"
#include "thingdef/thingdef_parse.cpp"
#include "thingdef/thingdef_properties.cpp"
#include "thingdef/thingdef_states.cpp"

#include "xlat/parse_xlat.cpp"
